# Generated by Django 3.2.9 on 2021-11-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulairevente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Entrprise', models.CharField(max_length=200, null=True)),
                ('Adresse_Email', models.CharField(max_length=200, null=True)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('banquaire', models.CharField(max_length=200, null=True)),
                ('OM', models.CharField(max_length=9, null=True)),
                ('MOMO', models.CharField(max_length=9, null=True)),
                ('nom_utilisateur', models.CharField(max_length=200, null=True)),
                ('mot_passe', models.CharField(max_length=200, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
