# Generated by Django 3.2.9 on 2021-11-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulairevente',
            name='Adresse_Email',
            field=models.EmailField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='formulairevente',
            name='MOMO',
            field=models.IntegerField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='formulairevente',
            name='OM',
            field=models.IntegerField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='formulairevente',
            name='banquaire',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formulairevente',
            name='telephone',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
