# Generated by Django 3.2.9 on 2021-11-26 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0002_auto_20211126_0640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formulairevente',
            new_name='Entreprise',
        ),
    ]
