# Generated by Django 3.2.9 on 2021-11-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0003_rename_formulairevente_entreprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('prenom', models.CharField(max_length=200, null=True)),
                ('Adresse_Email', models.EmailField(max_length=40, null=True)),
                ('nom_utulisateur', models.CharField(max_length=200, null=True)),
                ('mot_passe', models.CharField(max_length=200, null=True)),
                ('confirmer_votre_mot_de_passe', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
