# Generated by Django 3.2.9 on 2021-11-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire', '0004_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='confirmer_votre_mot_de_passe',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
